FROM nginx
COPY dist /usr/share/nginx/html
# ARG NODE_VERSION=18.16.0
# FROM node:${NODE_VERSION}-slim as build

# WORKDIR /app
# COPY ./package.json /app/package.json
# COPY ./package-lock.json /app/package-lock.json

# RUN npm install
# COPY . .
# RUN npm run build

# FROM nginx:alpine

# COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/build /usr/share/nginx/html