# fly.toml app configuration file generated for anniesextoncom on 2023-11-20T11:07:16-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anniesextoncom"
primary_region = "sea"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
